### PR TITLE
Add support for VK_EXT_line_rasterization

### PR DESCRIPTION
**Pull request by hevrard**
https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VK_EXT_line_rasterization

The new vkCmdSetLineStippleEXT is similar to the existing
vkCmdSetLineWidth, in that it sets part of the dynamic pipeline state.
The rest is classic extension boilerplate with getting/setting new
features and properties.

Bug: b/184781787

### CODE REVIEW

**Review by johnplate — APPROVED** [review]
LGTM, but better wait for one more approval

**Comment by hevrard** [comment]
@johnplate I forgot to `git add` a file, you may want to have a quick look again.

**Comment by johnplate** [comment]
> @johnplate I forgot to `git add` a file, you may want to have a quick look again.

Still LGTM. Now I know why I had the weird feeling that something is missing. :)

**Comment by hevrard** [comment]
Rebase on master now that the dynamic state changes have landed.

**Pull request merged**
