### PR TITLE
Do not store junk values into the state for imageview part of sampler descriptors

### PR DESCRIPTION
**Pull request by chrisforbes**

### CODE REVIEW

**Comment by yalcinmelihyasin** [comment]
In general, it seems pretty good.

Are we sure we do not leak any garbage information in other descriptor set types?

**Comment by AWoloszyn** [comment]
> In general, it seems pretty good.
> 
> Are we sure we do not leak any garbage information in other descriptor set types?

I think we can run into the same problems with the reverse. (ImageViews with garbage samplers for example)

**Comment by yalcinmelihyasin** [comment]
> > In general, it seems pretty good.
> > Are we sure we do not leak any garbage information in other descriptor set types?
> 
> I think we can run into the same problems with the reverse. (ImageViews with garbage samplers for example)

Then should we make this pr a bigger one with all the fixes? Or should we followed it with other prs? In that case, we should create an issue for it.

**Comment by chrisforbes** [comment]
Yes, there are various other case like this.

**Comment by chrisforbes** [comment]
I'll keep fixing those as I find them, in follow-ups.

**Pull request merged**
