### PR TITLE
Use existing mechanisms to find gapit in the smoketests.

### PR DESCRIPTION
**Pull request by pmuetschard**

### CODE REVIEW

**Comment by hevrard** [comment]
All smoketests fail on the CI runs?

**Comment by hevrard** [comment]
The change LGTM but the smoketest build fails on Windows, could this be a flake?

**Comment by hevrard** [comment]
(still failing to build smoketests on Windows)

**Comment by pmuetschard** [comment]
PTAL, it's finally doing what it's supposed to...

**Review by hevrard — APPROVED** [review]
Thanks for the cleanup!

**Pull request merged**
