### PR TITLE
Alternative take on context cancellation and mutate

### PR DESCRIPTION
**Pull request by hevrard**

### CODE REVIEW

**Comment by hevrard** [comment]
This approach may add to the object churning, we need to perf measurement to see the impact (but I'm currently facing issues when I try to use `gapit benchmark`)

**Comment by hevrard** [comment]
Discussion notes: keep this approach, but:
- move creation of the "ignore cancel context" at the top of Mutate functions
- in the database code: hoist the check for stopreason in above (separate commit)
- replace MustRead/MustWrite (and siblings like MustReadSlice etc) in all code by regular Read / Write with error checking
- rename MakeUncancellable to something like "IgnoreCancel"
- staterebuilder is very very unlikely to be cancelled, so it's OK to not treat the MustReadSlice etc... for now.

**Comment by hevrard** [comment]
I've updated the whole PR with 6 commits, to be reviewed in isolation.

Most commit are small, expect for the two commits that replace MustRead/MustWrite by Read/Write: these are big-but-boring commits that just adds error checking propagation.

Bug: b/149701723

**Comment by hevrard** [comment]
Fix #59

**Review by johnplate — APPROVED** [review]
The implementation in detail LGTM. I recommend to wait for another approval from someone who is more familiar with possible side-effects of a context that ignores cancellation and if is is safe not to check if the context was cancelled in every resolve.

**Comment by AWoloszyn** [comment]
Seems ok to me.

**Comment by hevrard** [comment]
Fix #59

**Review by pmuetschard — APPROVED** [review]

**Pull request merged**
